spring.application.name=agent
# spring.ai.bedrock.aws.region=us-east-1
# spring.ai.bedrock.aws.session-token=
spring.ai.bedrock.converse.chat.options.model=global.anthropic.claude-sonnet-4-5-20250929-v1:0
spring.ai.bedrock.converse.chat.options.temperature=0.7

# AgentCore Memory
agentcore.memory.memory-id=aiagent_memory-CnbqaoC8KM
agentcore.memory.long-term.auto-discovery=true

# AgentCore Memory
agentcore.memory.memory-id=
agentcore.memory.long-term.auto-discovery=true
